//PARA MOSTARAR TEXTO SIN FORMATO = (TEXTO PLANO)
console.log("COMO ESTAS HOY ")
//PARA MOSTRAR INFO
console.info("SOY INFOMACION")
// MENSAJE PARA alerta
console.warn("ESTOY EN ALERTA")

console.log(5+8)
// MENAJEPOR CONSOLA PARA GESTION DE TIEMPO
console.time()
edad=20
if(edad >= 18){
    console.log("ERES MAYOR DE EDAD")
}else{
    console.warn("ERES PULPIN")
}
console .timeEnd()